### ISSUE TITLE
Containerize the app

### ISSUE THREAD

**Issue by lopezpedres** [lopezpedres/ems-project#1]
- [x] Link the `requirements.txt` of the projects into the compose

- [x] Create `Dockerfile`

- [x] Create `docker-compose.yml`

- [x] Create a Postgres db that stores the data of the user

**Comment by lopezpedres** [comment]
```bash
flask db init
flask db migrate 
flask db upgrade
```

**Comment by mate-h** [comment]
Set the environment variable
```
FLASK_APP=entrypoint
```

**Comment by mate-h** [comment]
The issue was that when we try to run `flask db migrate` there is a password authentication faliure. this is configured with the `SQLALCHEMY_DB_URL` environment variable.

**Comment by lopezpedres** [comment]
Deleted the local Postgres.

**Comment by lopezpedres** [comment]
It worked by deleting the local postgres
