### ISSUE TITLE
Set up a development server

### ISSUE THREAD

**Issue by mate-h** [lopezpedres/ems-project#4]
- [x] 1. Simple server

   First, primitive version is as simple as setting env variables, and running `flask run`.

- [x] 2. https://vitejs.dev/

   Next, we want to enable HMR - Hot Module Replacement.
   When you press Save (Ctrl + S) in any file, the browser automatically reloads.

**Comment by lopezpedres** [comment]
Was able to create a production but when I did the connection with table plus I used localhost as the host and it worked. I thought I has to use the name of the container that was the database.

**Comment by mate-h** [comment]
Remember that Tableplus is an application that runs on your local computer that's why you use localhost. The only instance where you use the name of the container as the host name is when you're connecting from a docker service to another docker service within the internal docker network.

**Comment by mate-h** [comment]
This issue can be closed because as per Flask docs:
set the `FLASK_ENV=development` environment variable to enable HMR with flask.

Otherwise, the frontend part is completely separated in the docker service named `web` and it enabled for development server with vite.
